apiVersion: v1
kind: Namespace
metadata:
  name: dupla-gustavorostlucca
---
apiVersion: v1
kind: Pod
metadata:
  name: sentiment-api
  namespace: dupla-gustavorostlucca
  labels:
    app: sentiment-api
    dupla: gustavorost-lucca
spec:
  containers:
    - name: api
      image: ghcr.io/rodolfo-s-antunes/sentiment-api:v2
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: dupla-gustavorostlucca
spec:
  type: LoadBalancer
  selector:
    dupla: gustavorost-lucca
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
